name: C/C++ CI

on: [push]

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'Release:')"
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
     - uses: actions/checkout@master
     - name: make
       run: make LATESTTAG=Beta
     - name: Upload build artifact
       uses: actions/upload-artifact@v1
       with:
        name: binary
        path: HDR_Installer.nro
  upload:
    if: "contains(github.event.head_commit.message, 'Release:')"
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: binary
    - name: Upload Release
      uses: Genwald/create-release@eba889c
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release
        code: beta
        body: A homebrew application to install/manage HDR! Please report any bugs in the issues page of this repo.
        prerelease: false
        recreate: true
        assets: binary/HDR_Installer.nro:HDR_Installer.nro:application/octet-stream
